### ISSUE TITLE
ValueError

### ISSUE THREAD

**Issue by curryJ** [musyoku/gqn-datasets-translator#1]
when I use the merge.py to work to the 498 th/ 940,there is a error that ValueError: cannot reshape array of size 301121408 into shape (2000,15,64,64,3);
What makes me feel confused is the difference of data format.
Could you tell me the reason?
thx

**Comment by musyoku** [comment]
Hi
What dataset did you use?
(rooms_ring_camera / rooms_free_camera_no_object_rotations / rooms_free_camera_with_object_rotations / jaco / shepard_metzler_5_parts / shepard_metzler_7_parts / mazes)

**Comment by curryJ** [comment]
Thank you for you help.
I have found the reason. When I use the numpy.load(),the error also happend.
This is not because of the dataset format, and the reason is that when I run the code,I have no free space in my  computer disk,so the data is written Incompletely.
I run the code again giving it sufficient space  and the result is correct.
